name: build
on: [push, workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: pipx install hatch
      - run: sudo apt install libgtk-3-dev
      - run: hatch env create dev
