name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: amd64/archlinux:base
    steps:
      - uses: actions/checkout@v4
      - run: pacman -Syu --needed --noconfirm python-pipx python-wxpython
      - run: pipx install hatch
      - run: ~/.local/bin/hatch fmt --check
      - run: ~/.local/bin/hatch -vv env create dev
      - run: ~/.local/bin/hatch build
