name: lint
on: [push, workflow_dispatch]

jobs:
  lint:
    name: lint
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - run: brew install hatch
      - run: hatch fmt --check
