name: sanity
on: [push, workflow_dispatch]

jobs:
  lint:
    name: sanity
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: pipx install hatch
      - run: sudo apt install libgtk-3-dev
      - run: hatch -e dev -v run sanity
